# Generated by Django 5.0.7 on 2024-09-03 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_miniprojects_live_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
